### ISSUE TITLE
Investigate how to get crest information from DNT files.

### ISSUE THREAD

**Issue by benlei** [ben-lei/dncli#6]
Would be helpful to know what is crestable, and possibly even how to incorporate it into MAZE.

**Comment by spacem** [comment]
Take a look at itemtable_glyph.dnt

**Comment by benlei** [comment]
Thanks. glyphskilltable.dnt is the primary table, and that has a relation to itemtable_glyph.dnt.

I just haven't investigated how all the pieces are put together yet (including image icon).
